GC-79-added-create-repo-feature

diff --git a/utils/package_installer b/utils/package_installer
--- a/utils/package_installer
+++ b/utils/package_installer
@@ -231,6 +231,30 @@ check_and_install_git() {
     
 }
 
+check_and_install_gh() {
+
+    # checks for checking and installing gh
+    if ! gh --version  >/dev/null 2>&1; then
+        echo "gh cli is required"
+        echo "installing gh cli..."
+        if [ "${OS}" == "mac" ]; then
+            eval "$(getGumSpinnerOrLogger "gh is not installed, now installing gh") brew install gh"
+        elif [ "${OS}" == "gnu" ]; then
+            status_log $TYPE_INFO "going to update apt"
+            sudo apt update 2>&1
+            eval "$(getGumSpinnerOrLogger "gh is not installed, now installing gh") sudo apt-get install gh"
+        else
+            errMsg="Failed to install gh, OS ${OS} not supported at the moment"
+            echo $errMsg
+            status_log $TYPE_ERROR $errMsg
+            exit 1
+        fi
+    fi
+
+    extract_gh_cli_version
+    
+}
+
 check_and_install_yq() {
 
     # checks for checking and installing yq
@@ -463,6 +487,30 @@ extract_git_cli_version(){
             echo "Git version number: $version_number"
         else
             echo "Failed to extract version number from git version output."
+            return 0
+        fi
+
+        # Output the latest version
+        echo "      v$version_number - git" >> "$GRPL_WORKDIR/dependency_versions"
+    fi
+
+}
+
+extract_gh_cli_version(){
+
+    if ! grep -q "gh" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 
+
+        # Run gh version command and store the output
+        gh_version=$(gh --version)
+
+        # Extract version number using regular expression
+        regex="gh version ([0-9]+\.[0-9]+\.[0-9]+)"
+        version_number=""
+        if [[ $gh_version =~ $regex ]]; then
+            version_number=${BASH_REMATCH[1]}
+            echo "gh version number: $version_number"
+        else
+            echo "Failed to extract version number from gh version output."
             return 0
         fi
 
