make install work on minikube :-)

diff --git a/commands/cluster_commands/install b/commands/cluster_commands/install
--- a/commands/cluster_commands/install
+++ b/commands/cluster_commands/install
@@ -14,7 +14,7 @@ Usage:
   cluster install
 
 Variables:
-  TARGET_PLATFORM=CIVO / Kubernetes
+  TARGET_PLATFORM=CIVO / Kubernetes / minikube
 
   # general configurations
   GRAPPLE_VERSION = version of the grapple deployment (e.g. '0.2.1')
@@ -42,7 +42,7 @@ export BAGCLI_PROJECT_NAME=$1
 cli_log "cluster install BEGIN"
 
 # verify install target platform
-TARGET_PLATFORM=$(if [ "${TARGET_PLATFORM}" != "" ]; then echo ${TARGET_PLATFORM}; else gum choose "CIVO" "Kubernetes"; fi)
+TARGET_PLATFORM=$(if [ "${TARGET_PLATFORM}" != "" ]; then echo ${TARGET_PLATFORM}; else gum choose "minikube" "CIVO" "Kubernetes"; fi)
 echo "selected target platform: ${TARGET_PLATFORM}"
 
 # if CIVO, then pre-set the configuration params
@@ -63,7 +63,7 @@ if [ "${TARGET_PLATFORM}" = "CIVO" ]; then
   # if a CIVO cluster was selected, pre-set the configuration
   CIVO_CLUSTER_NAME=${CIVO_CLUSTER}
   CIVO_CLUSTER_ID=$(civo k8s show ${CIVO_CLUSTER} -o custom -f ID)
-  GRAPPLE_DNS=${CIVO_CLUSTER}
+  GRAPPLE_DNS=${CIVO_CLUSTER}.grapple-demo.com
 
   CIVO_CLUSTER_ID=$(if [ "${CIVO_CLUSTER_ID}" != "" ]; then echo ${CIVO_CLUSTER_ID}; else prompt_for_input_with_validation "Enter CIVO_CLUSTER_ID: " "Provide an ID for the cluster" "$non_empty_regex" "Input cannot be empty."; fi) || exit $?
   echo "selected civo cluster ID: ${CIVO_CLUSTER_ID}"
@@ -84,9 +84,43 @@ if [ "${TARGET_PLATFORM}" = "Kubernetes" ]; then
   KUBE_CONTEXT=$(if [ "${KUBE_CONTEXT}" != "" ]; then echo ${KUBE_CONTEXT}; else kubectl config get-contexts -o name | gum choose; fi)
 fi
 
+if [ "${TARGET_PLATFORM}" = "minikube" ]; then
+
+  if ! minikube addons list | grep enabled | grep ingress >/dev/null 2>&1; then
+    if [ "${AUTO_CONFIRM}" != "true" ]; then
+      gum confirm "Configure dns for your minikube?" || (echo "grapple cannot be installed without dns / ingress configuration" && exit)
+    fi
+    echo "enabling ingress addons for minikube"
+    minikube addons enable ingress
+    minikube addons enable ingress-dns
+  fi 
+
+  if ! grep -r $(minikube ip) /etc/resolver/ >/dev/null 2>&1; then
+echo "domain test
+nameserver $(minikube ip)
+search_order 1
+timeout 5" > /tmp/minikube-test
+
+    echo "please run the following commands before clicking on 'confirm':"
+    gum style \
+      --foreground 212 --border-foreground 212 --border double \
+      --align center --width 100 --margin "1 2" --padding "2 4" \
+      'sudo cp /tmp/minikube-test /etc/resolver/minikube-test'
+    if [ "${AUTO_CONFIRM}" != "true" ]; then
+      gum confirm "Proceed with ingress configuration?" || (echo "grapple cannot be installed without dns / ingress configuration" && exit)
+    else
+      sudo cp /tmp/minikube-test /etc/resolver/minikube-test
+    fi
+  fi 
+  GRAPPLE_DNS=test
+
+fi
+
 # Prompt for GRAPPLE_DNS, CIVO_CLUSTER_ID, etc. using gum
-GRAPPLE_DNS=$(if [ "${GRAPPLE_DNS}" != "" ]; then echo ${GRAPPLE_DNS}; else prompt_for_input_with_validation "Enter GRAPPLE_DNS: " "Valid DNS name is required" "$grpl_dns_regex" "Invalid DNS name format. Please try again."; fi) || exit $?
-echo "installing dns: ${GRAPPLE_DNS}"
+if [ "${TARGET_PLATFORM}" != "minikube" ]; then
+  GRAPPLE_DNS=$(if [ "${GRAPPLE_DNS}" != "" ]; then echo ${GRAPPLE_DNS}; else prompt_for_input_with_validation "Enter GRAPPLE_DNS: " "Valid DNS name is required" "$grpl_dns_regex" "Invalid DNS name format. Please try again."; fi) || exit $?
+  echo "installing dns: ${GRAPPLE_DNS}"
+fi
 
 GRAPPLE_VERSION=$(if [ "${GRAPPLE_VERSION}" != "" ]; then echo ${GRAPPLE_VERSION}; else gum choose "0.2.1" "0.2.0"; fi) || exit $? # not sure if both GRAPPLE_VERSION & VERSION are needed
 echo "installing grapple version: ${GRAPPLE_VERSION}"
@@ -97,11 +131,11 @@ echo "installing grapple version: ${GRAPPLE_VERSION}"
 cat <<EOF > ./values-override.yaml
 # Default values for grsf-init.
 
-clusterdomain: ${GRAPPLE_DNS}.grapple-demo.com
+clusterdomain: ${GRAPPLE_DNS}
 
 # Configuration
 config:
-  clusterdomain: ${GRAPPLE_DNS}.grapple-demo.com
+  clusterdomain: ${GRAPPLE_DNS}
   grapiversion: "0.0.1"
   gruimversion: "0.0.1"
   ssl: "true"
@@ -136,6 +170,7 @@ helm_deploy() {
 
     echo "Deploying $i with version $version"
 
+    # helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f ./values-override.yaml
     output=$(gum spin --show-output -- helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f ./values-override.yaml)
     if [[ "$output" == *"access denied"* ]]; then
       output=$(helm registry logout public.ecr.aws/${awsregistry} 2>&1)
@@ -152,8 +187,10 @@ helm_deploy() {
     fi
 }
 
-kubectl delete po grpl-dns-aws-route53-upsert-${GRAPPLE_DNS} >/dev/null 2>&1 | true
-kubectl run grpl-dns-aws-route53-upsert-${GRAPPLE_DNS} --image=grpl/dns-aws-route53-upsert --env="GRAPPLE_DNS=${GRAPPLE_DNS}" --env="CIVO_MASTER_IP=${CIVO_MASTER_IP}" --restart=Never
+if [ "${TARGET_PLATFORM}" = "CIVO" ]; then
+  kubectl delete po grpl-dns-aws-route53-upsert-${GRAPPLE_DNS} >/dev/null 2>&1 | true
+  kubectl run grpl-dns-aws-route53-upsert-${GRAPPLE_DNS} --image=grpl/dns-aws-route53-upsert --env="GRAPPLE_DNS=${GRAPPLE_DNS}" --env="CIVO_MASTER_IP=${CIVO_MASTER_IP}" --restart=Never
+fi
 
 echo 
 echo ----
@@ -170,7 +207,9 @@ if kubectl get deploy -n grpl-system grsf-init-cert-manager >/dev/null 2>&1; the
 fi
 
 # remove the DNS job again
-kubectl delete po grpl-dns-aws-route53-upsert-${GRAPPLE_DNS} 
+if [ "${TARGET_PLATFORM}" = "CIVO" ]; then
+  kubectl delete po grpl-dns-aws-route53-upsert-${GRAPPLE_DNS} 
+fi
 
 echo "wait for crossplane to be ready"
 if kubectl get deploy -n grpl-system crossplane >/dev/null 2>&1; then 
