GC-29 added error msg if deployment fails

diff --git a/commands/cluster_commands/install b/commands/cluster_commands/install
--- a/commands/cluster_commands/install
+++ b/commands/cluster_commands/install
@@ -283,7 +283,7 @@ helm_deploy() {
 
     echo "Deploying $i with version $version"
 
-    output=$(gum spin --title "Installing ${i} component" --show-output -- helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f /tmp/values-override.yaml)
+  if ! output=$(gum spin --title "Installing ${i} component" --show-output -- helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f /tmp/values-override.yaml); then
     if [[ "$output" == *"access denied"* ]]; then
       output=$(helm registry logout public.ecr.aws/${awsregistry} 2>&1)
       if [[ "$output" == "Removing login credentials for public.ecr.aws/${awsregistry}" ]]; then
@@ -298,7 +298,12 @@ helm_deploy() {
           exit 1
         fi
       fi
+    else 
+      echo "${i} Failed to Installed"
+      status_log $TYPE_ERROR "${i} Failed to Installed"
+      exit 1
     fi
+  fi
 
 }
 
