GC-95 added params

diff --git a/commands/cluster_commands/install b/commands/cluster_commands/install
--- a/commands/cluster_commands/install
+++ b/commands/cluster_commands/install
@@ -41,14 +41,152 @@ valid_args=(
     "EMAIL"
     "GITHUB_USERNAME"
     "GITLAB_USERNAME"
-    "CLOUD_PROVIDER"
-    "CLOUD_REGION"
-    "CLUSTER_ID"
-    "CLUSTER_NAME"
+    "KUBEFIRST_CLOUD_PROVIDER"
+    "KUBEFIRST_CLOUD_REGION"
+    "KUBEFIRST_CLUSTER_ID"
+    "KUBEFIRST_CLUSTER_NAME"
   )
 # check if values are already passed form terminal
 # if yes? then store then in the respective vars
 extract_input_params_from_cli $valid_args "grpl c i h" $(echo "$@")
+
+
+#-------------Functions-------------------
+
+extract_email_from_github_username() {
+
+
+  # Fetch the GitHub user's details (name) using the GitHub username
+  user_details=$(curl -s "https://api.github.com/users/$GITHUB_USERNAME")
+  USER_NAME=$(echo "$user_details" | jq -r '.name')
+
+  # Initialize variables
+  page=1
+  per_page=30
+
+  # Loop until we find the matching commit or there are no more events
+  while [ -z "$EMAIL" ]; do
+    # Fetch paginated events for the user
+    response=$(curl -s "https://api.github.com/users/$GITHUB_USERNAME/events/public?per_page=$per_page&page=$page")
+
+    # Validate that the response is valid JSON
+    if ! echo "$response" | jq empty > /dev/null 2>&1; then
+      echo "Error: Invalid JSON response from GitHub"
+      break
+    fi
+
+    # Check if response is empty, indicating no more pages
+    if [ "$(echo "$response" | jq length)" -eq 0 ]; then
+      break
+    fi
+
+    # Validate that the response is valid JSON
+    if ! echo "$response" | jq empty > /dev/null 2>&1; then
+      echo "Error: Invalid JSON response from GitHub"
+      break
+    fi
+
+    # Remove all spaces from the response
+    response=$(echo "$response" | tr -d '[:space:]')
+
+    # Check if response is empty, indicating no more pages
+    if [ "$(echo "$response" | jq length)" -eq 0 ]; then
+      break
+    fi
+
+    # Loop through each event in the response using jq to filter PushEvent
+    if ! echo "$response" | jq -e '.[] | select(.type == "PushEvent")' > /dev/null 2>&1; then
+      status_log $TYPE_ERROR "No Email found for $GITHUB_USERNAME"
+      exit 1
+    fi
+    for row in $(echo "$response" | jq -c '.[] | select(.type == "PushEvent")'); do
+      # Loop through all commits in the commit array
+      for commit in $(echo "$row" | jq -c '.payload.commits[]'); do
+        commit_name=$(echo "$commit" | jq -r '.author.name')
+        commit_email=$(echo "$commit" | jq -r '.author.email')
+        # Check if the commit author name matches the GitHub username
+        if [ "$commit_name" == "$GITHUB_USERNAME" ] || [ "$commit_name" == "$USER_NAME" ]; then
+          EMAIL=$commit_email
+          break 2  # Break from both loops if email is found
+        fi
+      done
+    done
+
+    # Move to the next page
+    page=$((page + 1))
+  done
+
+  # Output the result
+  if [ -n "$EMAIL" ]; then
+    echo "Email found: $EMAIL"
+  else
+    echo "No matching commit author found."
+  fi
+}
+
+
+extract_email_from_gitlab_username(){
+
+  # Get the GitLab user ID and name by username
+  user_details=$(curl -s "https://gitlab.com/api/v4/users?username=$GITLAB_USERNAME")
+  USER_ID=$(echo "$user_details" | jq -r '.[0].id')
+  USER_NAME=$(echo "$user_details" | jq -r '.[0].name')
+
+  if [ -z "$USER_ID" ]; then
+    status_log $TYPE_ERROR "No Email found for $GITLAB_USERNAME"
+    exit 1
+  fi
+
+  # Initialize pagination variables
+  page=1
+  per_page=30
+  # Loop until we find the matching commit or there are no more events
+  while [ -z "$EMAIL" ]; do
+    # Fetch paginated events for the user
+    response=$(curl -s "https://gitlab.com/api/v4/users/$USER_ID/events?per_page=$per_page&page=$page")
+
+    # Check if response is empty, indicating no more pages
+    if [ -z "$response" ] || [ "$(echo "$response" | jq length)" -eq 0 ]; then
+      status_log $TYPE_ERROR "No Email found for $GITLAB_USERNAME"
+      exit 1
+    fi
+
+    response=$(echo "$response" | tr -d '[:space:]')
+
+
+    # status_log $TYPE_INFO "response: $response"
+
+    # Loop through each event in the response using jq to filter PushEvent
+    for row in $(echo "$response" | jq -c '.[] | select(.action_name == "pushednew")'); do
+      # Extract the project ID and commit SHA from the event
+      project_id=$(echo "$row" | jq -r '.project_id')
+      commit_sha=$(echo "$row" | jq -r '.push_data.commit_to')
+
+      # Fetch the commit information from the project
+      commit_info=$(curl -s "https://gitlab.com/api/v4/projects/$project_id/repository/commits/$commit_sha")
+
+      # Extract the author name and email from the commit
+      commit_name=$(echo "$commit_info" | jq -r '.author_name')
+      commit_email=$(echo "$commit_info" | jq -r '.author_email')
+
+      # Check if the commit author name matches the GitLab username
+      if [ "$commit_name" == "$GITLAB_USERNAME" ] || [ "$commit_name" == "$USER_NAME" ]; then
+        EMAIL=$commit_email
+        break
+      fi
+    done
+
+    # Move to the next page
+    page=$((page + 1))
+  done
+
+  # Output the result
+  if [ -n "$EMAIL" ]; then
+    echo "Email found: $EMAIL"
+  else
+    echo "No matching commit author found."
+  fi
+}
 
 
 #------------ TARGET_PLATFORM Input-----------
@@ -256,48 +394,69 @@ if [ "${TARGET_PLATFORM}" = $Kubefirst ]; then
   # input variable that are required for kubefirst
 
   # ----------- Git Provider Input------------
-  GIT_PROVIDER=$(if [ "${GITHUB_USERNAME}" == "" ] && [ "${GITLAB_USERNAME}" == "" ]; then gum choose $GITHUB $GITLAB; else echo ""; fi)
-  echo "git provider: ${GIT_PROVIDER}"
+  
+  if [ $TTY == "enabled" ]; then
+    status_log $TYPE_INFO "Select Git Provider"
+    GIT_PROVIDER=$(if [ "${GITHUB_USERNAME}" == "" ] && [ "${GITLAB_USERNAME}" == "" ]; then gum choose $GITHUB $GITLAB; else echo ""; fi)
+    echo "git provider: ${GIT_PROVIDER}"
+  fi
 
-  if [ $GIT_PROVIDER == $GITHUB ]; then
+  if [[ $GIT_PROVIDER == $GITHUB ]] || [[ $GITHUB_USERNAME != "" ]]; then
     GITHUB_USERNAME=$(if [ "${GITHUB_USERNAME}" != "" ]; then echo ${GITHUB_USERNAME}; else [ $TTY == "enabled" ] && prompt_for_input_with_validation "Enter GITHUB_USERNAME: " "Provide the github username" "$non_empty_regex" "Input cannot be empty."; fi) || exit $?
     echo "github username: ${GITHUB_USERNAME}"
-  elif [ $GIT_PROVIDER == $GITLAB ]; then
+    status_log $TYPE_INFO "extracting email from github username"
+    [ "${GITHUB_USERNAME}" != "" ] && extract_email_from_github_username
+    status_log $TYPE_INFO "extracted email : $EMAIL from github username"
+
+  elif [[ $GIT_PROVIDER == $GITLAB ]] || [[ $GITLAB_USERNAME != "" ]]; then
     GITLAB_USERNAME=$(if [ "${GITLAB_USERNAME}" != "" ]; then echo ${GITLAB_USERNAME}; else [ $TTY == "enabled" ] && prompt_for_input_with_validation "Enter GITLAB_USERNAME: " "Provide the gitlab username" "$non_empty_regex" "Input cannot be empty."; fi) || exit $?
     echo "gitlab username: ${GITLAB_USERNAME}"
+    status_log $TYPE_INFO "extracting email from gitlab username"
+    [ "${GITLAB_USERNAME}" != "" ] && extract_email_from_gitlab_username
+    status_log $TYPE_INFO "extracted email : $EMAIL from gitlab username"
   fi
 
 
   #------------ Cloud Provider Input-----------
 
-  CLOUD_PROVIDER=$(if [ "${CLOUD_PROVIDER}" != "" ]; then echo ${CLOUD_PROVIDER}; else gum choose $K3D $AWS $Civo $DigitalOcean $GoogleCloud $Vultr; fi)
-  echo "cloud provider: ${CLOUD_PROVIDER}"
+  KUBEFIRST_CLOUD_PROVIDER=$(if [ "${KUBEFIRST_CLOUD_PROVIDER}" != "" ]; then echo ${KUBEFIRST_CLOUD_PROVIDER}; else [ $TTY == "enabled" ] && gum choose $K3D $AWS $Civo $DigitalOcean $GoogleCloud $Vultr; fi)
+  echo "cloud provider: ${KUBEFIRST_CLOUD_PROVIDER}"
 
   #------------ Cloud Region Input-----------
     
-  CLOUD_REGION=$(if [ "${CLOUD_REGION}" != "" ]; then echo ${CLOUD_REGION}; else [ $TTY == "enabled" ] && prompt_for_input_with_validation "Enter CLUSTER_REGION: " "Provide the cluster region" "$non_empty_regex" "Input cannot be empty."; fi) || exit $?
-  echo "cloud region: ${CLOUD_REGION}"
+  KUBEFIRST_CLOUD_REGION=$(if [ "${KUBEFIRST_CLOUD_REGION}" != "" ]; then echo ${KUBEFIRST_CLOUD_REGION}; else [ $TTY == "enabled" ] && prompt_for_input_with_validation "Enter CLUSTER_REGION: " "Provide the cluster region" "$non_empty_regex" "Input cannot be empty."; fi) || exit $?
+  echo "cloud region: ${KUBEFIRST_CLOUD_REGION}"
 
   #------------ Cluster ID Input-----------
     
-  CLUSTER_ID=$(if [ "${CLUSTER_ID}" != "" ]; then echo ${CLUSTER_ID}; else [ $TTY == "enabled" ] && prompt_for_input_with_validation "Enter CLUSTER_ID: " "Provide the cluster id" "$non_empty_regex" "Input cannot be empty."; fi) || exit $?
-  echo "cluster id: ${CLUSTER_ID}"
+  KUBEFIRST_CLUSTER_ID=$(if [ "${KUBEFIRST_CLUSTER_ID}" != "" ]; then echo ${KUBEFIRST_CLUSTER_ID}; else [ $TTY == "enabled" ] && prompt_for_input_with_validation "Enter KUBEFIRST_CLUSTER_ID: " "Provide the cluster id" "$non_empty_regex" "Input cannot be empty."; fi) || exit $?
+  echo "cluster id: ${KUBEFIRST_CLUSTER_ID}"
 
   #------------ Cluster Name Input-----------
     
-  CLUSTER_NAME=$(if [ "${CLUSTER_NAME}" != "" ]; then echo ${CLUSTER_NAME}; else [ $TTY == "enabled" ] && prompt_for_input_with_validation "Enter CLUSTER_NAME: " "Provide the cluster name" "$non_empty_regex" "Input cannot be empty."; fi) || exit $?
-  echo "cluster name: ${CLUSTER_NAME}"
+  KUBEFIRST_CLUSTER_NAME=$(if [ "${KUBEFIRST_CLUSTER_NAME}" != "" ]; then echo ${KUBEFIRST_CLUSTER_NAME}; else [ $TTY == "enabled" ] && prompt_for_input_with_validation "Enter KUBEFIRST_CLUSTER_NAME: " "Provide the cluster name" "$non_empty_regex" "Input cannot be empty."; fi) || exit $?
+  echo "cluster name: ${KUBEFIRST_CLUSTER_NAME}"
 
 
   echo "DNS: $GRAPPLE_DNS"
 
 fi
 
+
 # Prompt for GRAPPLE_DNS, CIVO_CLUSTER_ID, etc. using gum
-if [ "${TARGET_PLATFORM}" != $Minikube ]; then
+complete_domain="" 
+if [ "${TARGET_PLATFORM}" != $Minikube ] && [ "${TARGET_PLATFORM}" != $Kubefirst ]; then
   GRAPPLE_DNS=$(if [ "${GRAPPLE_DNS}" != "" ]; then echo ${GRAPPLE_DNS}; else [ $TTY == "enabled" ] && prompt_for_input_with_validation "Enter GRAPPLE_DNS: " "Valid DNS name is required" "$grpl_dns_regex" "Invalid DNS name format. Please try again."; fi) || exit $?
   echo "installing dns: ${GRAPPLE_DNS}"
+  #----------- creating complete domain --------
+  if host $(extract_domain_name "$GRAPPLE_DNS") 2>&1 > /dev/null;then
+    complete_domain=$GRAPPLE_DNS
+  else 
+    complete_domain=${GRAPPLE_DNS}${GRAPPLE_DOMAIN}
+  fi
 fi
+
+
 
 #----------- GRAPPLE_VERSION Input --------
 if [ "${GRAPPLE_VERSION}" != "" ]; then 
@@ -307,18 +466,11 @@ GRAPPLE_VERSION=$(if [ "${GRAPPLE_VERSION}" != "" ]; then echo ${GRAPPLE_VERSION
 echo "installing grapple version: ${GRAPPLE_VERSION}"
 
 
-#----------- creating complete --------
-complete_domain="" 
-if host $(extract_domain_name "$GRAPPLE_DNS") 2>&1 > /dev/null;then
-  complete_domain=$GRAPPLE_DNS
-else 
-  complete_domain=${GRAPPLE_DNS}${GRAPPLE_DOMAIN}
-fi
-
 #----------- ORGANIZATION default value --------
 if [ "${ORGANIZATION}" == "" ]; then 
   ORGANIZATION="grapple solutions AG"
 fi
+
 
 #----------- Email validation and default value --------
 if [ "${EMAIL}" != "" ]; then 
@@ -350,14 +502,15 @@ config:
   GRAPPLE_DNS: ${complete_domain}
   GRAPPLE_VERSION: ${GRAPPLE_VERSION}
   GRAPPLE_LICENSE: "free"
-  CLOUD_PROVIDER: ${CLOUD_PROVIDER}
-  CLOUD_REGION: ${CLOUD_REGION}
-  CLUSTER_ID: ${CLUSTER_ID}
-  CLUSTER_NAME: ${CLUSTER_NAME}
+  CLOUD_PROVIDER: ${KUBEFIRST_CLOUD_PROVIDER}
+  CLOUD_REGION: ${KUBEFIRST_CLOUD_REGION}
+  CLUSTER_ID: ${KUBEFIRST_CLUSTER_ID}
+  CLUSTER_NAME: ${KUBEFIRST_CLUSTER_NAME}
 # Additional configurations omitted for brevity
 EOF
 
 cat /tmp/values-override.yaml
+
 
 # Use gum to confirm before proceeding
 if [ "${AUTO_CONFIRM}" != "true" ]; then
@@ -370,10 +523,10 @@ if [ "${AUTO_CONFIRM}" != "true" ]; then
     status_log $TYPE_DEFAULT "CIVO_EMAIL_ADDRESS: ${CIVO_EMAIL_ADDRESS}"
     status_log $TYPE_DEFAULT "CLUSTER_IP: ${CLUSTER_IP}"
   elif [ ${TARGET_PLATFORM} == $Kubefirst ]; then
-    status_log $TYPE_DEFAULT "CLOUD_PROVIDER: ${CLOUD_PROVIDER}"
-    status_log $TYPE_DEFAULT "CLOUD_REGION: ${CLOUD_REGION}"
-    status_log $TYPE_DEFAULT "CLUSTER_ID: ${CLUSTER_ID}"
-    status_log $TYPE_DEFAULT "CLUSTER_NAME: ${CLUSTER_NAME}"
+    status_log $TYPE_DEFAULT "KUBEFIRST_CLOUD_PROVIDER: ${KUBEFIRST_CLOUD_PROVIDER}"
+    status_log $TYPE_DEFAULT "KUBEFIRST_CLOUD_REGION: ${KUBEFIRST_CLOUD_REGION}"
+    status_log $TYPE_DEFAULT "KUBEFIRST_CLUSTER_ID: ${KUBEFIRST_CLUSTER_ID}"
+    status_log $TYPE_DEFAULT "KUBEFIRST_CLUSTER_NAME: ${KUBEFIRST_CLUSTER_NAME}"
   fi
 
   status_log $TYPE_DEFAULT "GRAPPLE_VERSION: ${GRAPPLE_VERSION}"
