GC-128-added-retires-in-grpl-c-i-helm-deploy

diff --git a/commands/cluster_commands/install b/commands/cluster_commands/install
--- a/commands/cluster_commands/install
+++ b/commands/cluster_commands/install
@@ -632,7 +632,7 @@ if [ "$values_yaml_file_names" != "" ]; then
   values_yaml_file_names=$(echo "$values_yaml_file_names" | awk -v grpl_workdir="$GRPL_WORKDIR" '{gsub("values-templates", "\"" grpl_workdir "/values-templates\"")}1')
   values_yaml_file_names=$(echo "$values_yaml_file_names" | sed 's/"//g')
 fi
-loggedOut="false"
+retries=0
 helm_deploy() {
 
   i=$1
@@ -657,26 +657,22 @@ helm_deploy() {
   fi
 
   if ! eval "$(getGumSpinnerOrLogger "Installing ${i} component") helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f /tmp/values-override.yaml $values_yaml_file_names $Kubefirst_values" >/dev/null; then
-    
-    if [[ "$loggedOut" = "true" ]]; then
-      echo "${i} Failed to Installed"
-      status_log $TYPE_ERROR "${i} Failed to Installed due to following error"
-      eval "$(getGumSpinnerOrLogger "Installing ${i} component") helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f /tmp/values-override.yaml $values_yaml_file_names $Kubefirst_values"  >&2  
-      exit 1
+    ((retries+=1))
+    status_log $TYPE_INFO "Retry ${retries} - ${i} Failed to Install"
+    if [[ $retries == 3 ]]; then
+        status_log $TYPE_INFO "We tried retrying 3 times and tried logging out of public.ecr.aws registry but it failed, please run 'helm registry logout public.ecr.aws/<repo>' and try again"
+        echo "${i} Failed to Installed"
+        status_log $TYPE_ERROR "${i} Failed to Installed due to following error"
+        eval "$(getGumSpinnerOrLogger "Installing ${i} component") helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f /tmp/values-override.yaml $values_yaml_file_names $Kubefirst_values"  >&2  
+        exit 1
+    else 
+      if helm registry logout public.ecr.aws >/dev/null 2>&1; then
+        status_log $TYPE_INFO "logged out of public.ecr.aws registry"
+        status_log $TYPE_INFO "trying again"
+      fi
+      helm_deploy $i
     fi
 
-    if helm registry logout public.ecr.aws >/dev/null 2>&1; then
-      loggedOut="true"
-      status_log $TYPE_INFO "logged out of public.ecr.aws registry"
-      status_log $TYPE_INFO "trying again"
-      helm_deploy $i
-    else 
-      status_log $TYPE_INFO "We tried logging out of public.ecr.aws registry but it failed, please run 'helm registry logout public.ecr.aws/<repo>' and try again"
-      echo "${i} Failed to Installed"
-      status_log $TYPE_ERROR "${i} Failed to Installed due to following error"
-      eval "$(getGumSpinnerOrLogger "Installing ${i} component") helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f /tmp/values-override.yaml $values_yaml_file_names $Kubefirst_values"  >&2  
-      exit 1
-    fi
   fi
 
 }
