GC-17 created cluster install for aws v1

diff --git a/commands/aws_commands/install b/commands/aws_commands/install
--- a/commands/aws_commands/install
+++ b/commands/aws_commands/install
@@ -35,9 +35,6 @@ valid_args=(
     "EMAIL"
     "INSTALL_KUBEBLOCKS"
     "STAGE"
-    "AWSID"
-    "AWSKEY"
-    "MONITORING"
     "SSL"
   )
 # check if values are already passed form terminal
@@ -176,10 +173,8 @@ else
 fi
 
 
-
 PROVIDER_CLUSTER_NAME=${AWS}
 export CLUSTERDOMAIN=${complete_domain}
-status_log $TYPE_INFO "CLUSTERDOMAIN: ${CLUSTERDOMAIN}"
 
 cat <<EOF > /tmp/values-override.yaml
 # Default values for grsf-init.
@@ -198,8 +193,8 @@ config:
   ssl: "$SSL"
   sslissuer: "$SSL_ISSUER"
   MONITORING: "$MONITORING"
-  AWSID: ${AWSID}
-  AWSKEY: ${AWSKEY}
+  GRPL_AWSID: ${GRPL_AWSID}
+  GRPL_AWSKEY: ${GRPL_AWSKEY}
   GRAPPLE_DNS: ${complete_domain}
   GRAPPLE_VERSION: ${GRAPPLE_VERSION}
   GRAPPLE_LICENSE: ${GRAPPLE_LICENSE}
@@ -228,8 +223,8 @@ if [ "${AUTO_CONFIRM}" != "true" ]  && [ "$TTY" == "enabled" ]; then
   status_log $TYPE_DEFAULT "SSL_ISSUER: ${SSL_ISSUER}"
   status_log $TYPE_DEFAULT "PROVIDER_CLUSTER_NAME: ${PROVIDER_CLUSTER_NAME}"
   status_log $TYPE_DEFAULT "MONITORING: ${MONITORING}"
-  status_log $TYPE_DEFAULT "AWSID: ${AWSID}"
-  status_log $TYPE_DEFAULT "AWSKEY: ${AWSKEY}"
+  status_log $TYPE_DEFAULT "GRPL_AWSID: ${GRPL_AWSID}"
+  status_log $TYPE_DEFAULT "GRPL_AWSKEY: ${GRPL_AWSKEY}"
 
   gum confirm "Proceed with deployment using the values above?" || (status_log $TYPE_ERROR "Failed to install grpl" && exit 1)
 fi
@@ -249,196 +244,158 @@ fi
 echo 
 echo ----
 
-
-if [ "$GITPOD_WORKSPACE_ID" != "" ]; then
-    if [ "$INSTALL" = "" ]; then
-        INSTALL="minimal"
-    fi
-fi
-
-retries=0
-
 helm_deploy() {
-    i=$1
-    n=$2 # define namespace
-    v=$3 # define injected values
-    if [ "$1" = "base" ]; then WAIT=" --wait"; else WAIT=""; fi
-    echo "------"
-    echo "deploying: $i"
-    # helm dep up k8s/$i
-    # envsubst < k8s/$i/values-override.yaml
-    # --wait makes it slower...
-    # envsubst < k8s/$i/values-override.yaml | helm upgrade --install $i k8s/$i -n ${NS} --wait --create-namespace -f - 
-    # envsubst < k8s/$i/values-override.yaml | helm upgrade --install $i k8s/$i -n ${NS} --create-namespace -f - 
-    if [ "$stage" != "prd" ]; then 
-        ext="-${stage}"
-    else   
-        ext=""
+
+  i=$1
+  v=${2:-$GRAPPLE_VERSION}
+  if [ "$v" != "" ]; then 
+    version="--version ${v}"
+  else
+    version=""
+  fi
+    
+
+  echo "Deploying $i with version $version"
+
+  if [ "${TARGET_PLATFORM}" = $Kubefirst ]; then
+    if [[ "$(echo "${KUBEFIRST_CLOUD_PROVIDER}" | tr '[:upper:]' '[:lower:]')" == "$(echo "${K3D}" | tr '[:upper:]' '[:lower:]')" ]]; then
+      Kubefirst_values=" -f ${GRPL_WORKDIR}/template-files/values-kubefirst-k3d.yaml "
+    else
+      Kubefirst_values=" -f ${GRPL_WORKDIR}/template-files/values-kubefirst.yaml "
     fi
-    if [ "$2" != "" ]; then NAMESPACE=" -n $2 "; else NAMESPACE=" -n ${NS} "; fi
-    if [ "$3" != "" ]; then VALUES=" -f $3 "; fi  
+  else
+    Kubefirst_values=" -f $dependencies_path/values-integration-aws.yaml "
+  fi
 
+  if ! eval "$(getGumSpinnerOrLogger "Installing ${i} component") helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f /tmp/values-override.yaml $values_yaml_file_names $Kubefirst_values" >/dev/null; then
+    ((retries+=1))
+    status_log $TYPE_INFO "Retry ${retries} - ${i} Failed to Install"
+    if [[ $retries == 3 ]]; then
+        status_log $TYPE_INFO "We tried retrying 3 times and tried logging out of public.ecr.aws registry but it failed, please run 'helm registry logout public.ecr.aws/<repo>' and try again"
+        echo "${i} Failed to Installed"
+        status_log $TYPE_ERROR "${i} Failed to Installed due to following error"
+        eval "$(getGumSpinnerOrLogger "Extracting Error") helm upgrade --install $i oci://public.ecr.aws/${awsregistry}/$i -n ${NS} ${version} --create-namespace -f /tmp/values-override.yaml $values_yaml_file_names $Kubefirst_values"  >&2  
+        exit 1
+    else 
+      if helm registry logout public.ecr.aws >/dev/null 2>&1; then
+        status_log $TYPE_INFO "logged out of public.ecr.aws registry"
+        status_log $TYPE_INFO "trying again"
+      fi
+      helm_deploy $i
+    fi
 
-    echo
-    echo "------"
-    echo "helm upgrade --install ${i} oci://public.ecr.aws/${awsregistry}/${i}${ext} ${NAMESPACE} --create-namespace ${WAIT} ${VALUES} # + values-override.yaml"
-    echo "------"
-    envsubst < $dependencies_path/values-override.yaml | helm upgrade --install ${i} oci://public.ecr.aws/${awsregistry}/${i}${ext} ${NAMESPACE} --create-namespace ${WAIT} ${VALUES} -f -
+  fi
+
 }
 
-echo "install the metrics server"
-kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
-
-helm_deploy grsf-init
-
-if [ "${STAGE}" = "awstim" ] && [ "$(uname -s)" != "Darwin" ]; then
- echo "prepare external secrets for tim"
- echo -n "${AWSID}" > ./access-key
- echo -n "${AWSKEY}" > ./secret-access-key
- sleep 1
- kubectl -n ${NS} create secret generic awssm-secret --from-file=./access-key  --from-file=./secret-access-key 2>/dev/null || true
-else
- if [ "$(uname -s)" = "Darwin" ]; then
-  if [ "${AWSID}" = "" ]; then
-    status_log $TYPE_ERROR "AWSID is empty, please set AWSID and AWSKEY"
-    exit 99
-  fi
-  echo -n "${AWSID}" > ./access-key
-  echo -n "${AWSKEY}" > ./secret-access-key
-  kubectl -n kube-system delete secret awssm-secret
-  kubectl -n kube-system create secret generic awssm-secret --from-file=./access-key  --from-file=./secret-access-key 2>/dev/null # || true
-  kubectl -n grpl-system delete secret awssm-secret || true
-  kubectl -n grpl-system create secret generic awssm-secret --from-file=./access-key  --from-file=./secret-access-key 2>/dev/null # || true
- else
-  echo "prepare external secrets"
-  echo -n "${AWSID}" > ./access-key
-  echo -n "${AWSKEY}" > ./secret-access-key
-  sleep 1
-  kubectl -n ${NS} create secret generic awssm-secret --from-file=./access-key  --from-file=./secret-access-key 2>/dev/null || true
- fi
+if [ "${INSTALL_KUBEBLOCKS}" == "true" ]; then
+    status_log $TYPE_INFO "Installing kubeblocks in background"
+    kubeblocks_installation >/dev/null 2>&1 &
 fi
 
-status_log $TYPE_INFO "wait for cert-manager to be ready"
+if ! host $(extract_domain_name "$GRAPPLE_DNS") 2>&1 > /dev/null; then
+  status_log $TYPE_INFO "Deploying grpl-dns-aws-route53-upsert"
+  kubectl delete po -n default grpl-dns-aws-route53-upsert-${GRAPPLE_DNS} >/dev/null 2>&1 | true
+  kubectl run -n default grpl-dns-aws-route53-upsert-${GRAPPLE_DNS} --image=grpl/dns-aws-route53-upsert --env="GRAPPLE_DNS=${complete_domain}" --env="CIVO_MASTER_IP=${CLUSTER_IP}" --restart=Never
+fi
+
+echo 
+echo ----
+
+helm_deploy grsf-init 
+status_log $TYPE_INFO "waiting for grsf-init to be ready"
+
+echo "wait for cert-manager to be ready"
 if helm get -n kube-system notes traefik >/dev/null 2>&1; then 
-    CRD=Middleware && echo "wait for ${CRD} to be deployed:" && until kubectl explain ${CRD} >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "${CRD} deployed"
+    CRD=Middleware && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
 fi
 if kubectl get deploy -n grpl-system grsf-init-cert-manager >/dev/null 2>&1; then 
     kubectl wait deployment -n ${NS} grsf-init-cert-manager --for condition=Available=True --timeout=300s
-    CRD=ClusterIssuer && echo "wait for ${CRD} to be deployed:" && until kubectl explain ${CRD} >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "${CRD} deployed"
+    CRD=ClusterIssuer && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
 fi
-if kubectl get deploy -n grpl-system crossplane >/dev/null 2>&1; then 
-    CRD=Provider && echo "wait for ${CRD} to be deployed:" && until kubectl explain ${CRD} >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "${CRD} deployed"
-fi
-if kubectl get deploy -n grpl-system grsf-init-external-secrets-webhook >/dev/null 2>&1; then 
-    CRD=ExternalSecrets && echo "wait for ${CRD} to be deployed:" && until kubectl explain ${CRD} >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "${CRD} deployed"
-    echo "wait for external-secrets to be ready"
-    kubectl wait deployment -n ${NS} grsf-init-external-secrets-webhook --for condition=Available=True --timeout=300s
-fi 
-
-status_log $TYPE_SUCCESS "grsf-init is Installed"
-
-helm_deploy grsf
-status_log $TYPE_INFO "wait for grsf to be ready"
-sleep 10
-if kubectl get -n ${NS} $(kubectl get deploy -n ${NS} -o name | grep provider-civo) >/dev/null 2>&1; then 
-    kubectl wait -n ${NS} provider.pkg.crossplane.io/provider-civo --for condition=Healthy=True --timeout=300s
-    echo "wait for provider-civo to be ready"
-    CRD=providerconfigs.civo.crossplane.io  && echo "wait for ${CRD} to be deployed:" && until kubectl explain ${CRD} >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "${CRD} deployed"
-fi 
-for i in $(kubectl get pkg -n ${NS} -o name); do 
-    kubectl wait -n ${NS} $i --for condition=Healthy=True --timeout=300s;
-done
-if kubectl get -n ${NS} $(kubectl get deploy -n ${NS} -o name | grep provider-helm) >/dev/null 2>&1; then 
-    CRD=providerconfigs.helm.crossplane.io  && echo "wait for ${CRD} to be deployed:" && until kubectl explain ${CRD} >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "${CRD} deployed"
-fi 
-if kubectl get -n ${NS} $(kubectl get deploy -n ${NS} -o name | grep provider-kubernetes) >/dev/null 2>&1; then 
-    CRD=providerconfigs.kubernetes.crossplane.io  && echo "wait for ${CRD} to be deployed:" && until kubectl explain ${CRD} >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "${CRD} deployed"
-fi 
-
-status_log $TYPE_SUCCESS "grsf is Installed"
-helm_deploy grsf-config
-status_log $TYPE_INFO "wait for grsf-config to be ready"
-
-if [[ "$STAGE" != "aws"* ]]; then # cluster autoscaler patching not required for AWS clusters...
-    if kubectl get deploy -n kube-system cluster-autoscaler >/dev/null 2>&1; then
-        if ! kubectl get deploy -n kube-system -o yaml | grep scan-interval >/dev/null 2>&1; then
-            echo "amend cluster-autoscaler config"
-            if [[ "$STAGE" = *"demo"* ]]; then
-                kubectl patch deployment cluster-autoscaler -n kube-system --type='json' --patch='[
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--scan-interval=30s" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--nodes=2:10:workers" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--min-replica-count=1" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--cordon-node-before-terminating=true" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--scale-down-utilization-threshold=2" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--scale-down-unneeded-time=60m" }
-                    ]'
-            elif [[ "$STAGE" = *"jcs"* ]] || [[ "$STAGE" = *"mbd"* ]]; then
-                kubectl patch deployment cluster-autoscaler -n kube-system --type='json' --patch='[
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--scan-interval=30s" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--nodes=2:10:workers" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--min-replica-count=1" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--cordon-node-before-terminating=true" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--scale-down-utilization-threshold=2" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--scale-down-unneeded-time=60m" }
-                    ]'
-            else
-                kubectl patch deployment cluster-autoscaler -n kube-system --type='json' --patch='[
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--scan-interval=30s" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--nodes=2:10:workers" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--min-replica-count=1" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--cordon-node-before-terminating=true" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--scale-down-utilization-threshold=2" },
-                        { "op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--scale-down-unneeded-time=10m" }
-                    ]'
-            fi
-        fi
-    fi
-fi
-
-
-status_log $TYPE_SUCCESS "grsf-config is Installed"
-
-# install orm-monitoring helm chart
-if [ "$MONITORING" = true ]; then
-    if [ "${SSL}" != true ]; then
-        MONITORINGSSL=" --set kube-prometheus.prometheus.ingress.tls=false --set grafana-operator.grafana.ingress.tls=false "
-    else   
-        MONITORINGSSL=""
-    fi
-fi
-
-
-if [ "$USER" = "gitpod" ]; then 
-    helm_deploy grsf-monitoring grsf-monitoring
-    helm_deploy grsf-integration ${NS} $dependencies_path/values-integration-grpl.yaml
-elif [[ "$STAGE" = "aws"* ]]; then
-    helm_deploy grsf-monitoring grsf-monitoring $dependencies_path/values-integration-aws-monitoring.yaml
-    helm_deploy grsf-integration ${NS} $dependencies_path/values-integration-aws.yaml
-    export CLUSTER_NAME=$CLUSTER_NAME
-    $dependencies_path/createIRSA-AMPIngest.sh
-elif [[ "$STAGE" = *"demo"* ]]; then 
-    helm_deploy grsf-integration 
-elif [[ "$STAGE" = "uat" ]]; then 
-    helm_deploy grsf-monitoring grsf-monitoring
-    helm_deploy grsf-integration ${NS} $dependencies_path/values-integration-grpl.yaml
-elif [[ "$STAGE" = "dev" ]]; then 
-    helm_deploy grsf-monitoring grsf-monitoring
-    helm_deploy grsf-integration ${NS} $dependencies_path/values-integration-grpl.yaml
-elif [[ "$STAGE" = *"grpl"* ]]; then 
-    helm_deploy grsf-monitoring grsf-monitoring
-    helm_deploy grsf-integration ${NS} $dependencies_path/values-integration-grpl.yaml
-else
-    helm_deploy grsf-integration 
-fi
-
-rm /tmp/values-override.yaml
-
-status_log $TYPE_SUCCESS "grsf-integration is Installed"
 
 # remove the DNS job again
 if ! host $(extract_domain_name "$GRAPPLE_DNS") 2>&1 > /dev/null; then
   kubectl delete po -n default grpl-dns-aws-route53-upsert-${GRAPPLE_DNS} 
 fi
+
+echo "wait for crossplane to be ready"
+if kubectl get deploy -n grpl-system crossplane >/dev/null 2>&1; then 
+    CRD=Provider && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
+fi
+
+echo "wait for external-secrets to be ready"
+if kubectl get deploy -n grpl-system grsf-init-external-secrets-webhook >/dev/null 2>&1; then 
+    CRD=ExternalSecrets && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
+    echo "wait for external-secrets to be ready"
+    kubectl wait deployment -n ${NS} grsf-init-external-secrets-webhook --for condition=Available=True --timeout=300s
+fi 
+
+
+status_log $TYPE_SUCCESS "grsf-init is Installed"
+
+echo 
+echo ----
+echo "Ready for grsf deployment"
+
+helm_deploy grsf
+status_log $TYPE_INFO "waiting for grsf to be ready"
+
+echo "wait for providerconfigs to be ready"
+sleep 10
+if kubectl get -n ${NS} $(kubectl get deploy -n ${NS} -o name | grep provider-civo) >/dev/null 2>&1; then 
+    kubectl wait -n ${NS} provider.pkg.crossplane.io/provider-civo --for condition=Healthy=True --timeout=300s
+    echo "wait for provider-civo to be ready"
+    CRD=providerconfigs.civo.crossplane.io  && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
+fi 
+
+for i in $(kubectl get pkg -n ${NS} -o name); do 
+    kubectl wait -n ${NS} $i --for condition=Healthy=True --timeout=300s;
+done
+if kubectl get -n ${NS} $(kubectl get deploy -n ${NS} -o name | grep provider-helm) >/dev/null 2>&1; then 
+    CRD=providerconfigs.helm.crossplane.io  && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
+fi 
+if kubectl get -n ${NS} $(kubectl get deploy -n ${NS} -o name | grep provider-kubernetes) >/dev/null 2>&1; then 
+    CRD=providerconfigs.kubernetes.crossplane.io  && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
+fi 
+
+
+status_log $TYPE_SUCCESS "grsf is Installed"
+
+echo 
+echo ----
+
+helm_deploy grsf-config 
+status_log $TYPE_INFO "waiting for grsf-config to be applied"
+
+CRD=compositemanagedapis.grsf.grpl.io && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
+CRD=compositemanageduimodules.grsf.grpl.io && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
+CRD=compositemanageddatasources.grsf.grpl.io && echo "wait for $CRD to be deployed:" && until kubectl explain $CRD >/dev/null 2>&1; do echo -n .; sleep 1; done && echo "$CRD deployed"
+for i in $(kubectl get xrd -o name); do 
+  kubectl wait --for=condition=Offered $i;
+done
+
+status_log $TYPE_SUCCESS "grsf-config is Installed"
+
+helm_deploy grsf-integration
+status_log $TYPE_INFO "waiting for grsf-config to be ready"
+
+echo 
+echo ----
+echo "enable ssl"
+kubectl apply -f $GRPL_WORKDIR/files/clusterissuer.yaml
+
+echo "check all crossplane packages are ready"
+for i in $(kubectl get pkg -o name); do kubectl wait --for=condition=Healthy $i; done
+
+status_log $TYPE_SUCCESS "grsf-integration is Installed"
+
+cli_log "cluster install END"
+
+
+rm /tmp/values-override.yaml
+
+status_log $TYPE_SUCCESS "Successfuly Installed grpl"
 
 
 if [ "${INSTALL_KUBEBLOCKS}" == "true" ]; then
@@ -446,4 +403,6 @@ if [ "${INSTALL_KUBEBLOCKS}" == "true" ]; then
   wait
   status_log $TYPE_SUCCESS "kubeblocks is installed"
 fi
+
+
 
